<?php

use CodeIgniter\Router\RouteCollection;

/**
 * @var RouteCollection $routes
 */
$routes->get('/home/index', 'Home::index');
$routes->get('/home/dashboard', 'Home::dashboard');
$routes->get('/home/login', 'Home::login');
$routes->get('/home/logout', 'Home::logout');
$routes->add('/home/aksi_login', 'Home::aksi_login');
$routes->get('home/aksi_register', 'Home::aksi_register');
$routes->get('home/barang', 'Home::barang');
$routes->get('home/pemesanan', 'Home::pemesanan');
$routes->get('home/Pemesanan', 'Home::Pemesanan');
$routes->get('home/tbarang', 'Home::tbarang');
$routes->post('home/aksi_tbarang', 'Home::aksi_tbarang');
$routes->post('home/aksi_tbarangk', 'Home::aksi_tbarangk');
$routes->add('/home/ebarang/(:num)','Home::ebarang/$1');
$routes->add('/home/aksi_ebarang','Home::aksi_ebarang');
$routes->post('/home/aksi_ebarangk','Home::aksi_ebarangk');
$routes->add('/home/sdbarang/(:num)','Home::sdbarang/$1');
$routes->add('/home/sdbarangk/(:num)','Home::sdbarangk/$1');
$routes->add('/home/rsbarang/(:num)','Home::rsbarang/$1');
$routes->add('/home/rsbarangk/(:num)','Home::rsbarangk/$1');
$routes->add('/home/rbarang','Home::rbarang');
$routes->get('/home/user','Home::user');
$routes->add('/home/rkeranjang','Home::rkeranjang');
$routes->add('/home/setting','Home::setting');
$routes->post('home/aksi_esetting', 'Home::aksi_esetting');
$routes->add('/home/euser/(:num)','Home::euser/$1');
$routes->post('home/aksi_euser', 'Home::aksi_euser');
$routes->add('/home/tuser','Home::tuser');
$routes->post('home/aksi_tuser', 'Home::aksi_tuser');
$routes->add('/home/keranjang/(:num)','Home::keranjang/$1');
$routes->add('/home/hPesanan','Home::hPesanan');
$routes->add('/home/infopesanan','Home::infopesanan');
$routes->add('/home/riwayat_p','Home::riwayat_p');
$routes->add('/home/notfound','Home::notfound');
$routes->add('/home/save_cart','Home::save_cart');
$routes->add('/home/bayar','Home::bayar');
$routes->add('/home/cash','Home::cash');
$routes->add('/home/barangmasuk','Home::barangmasuk');
$routes->add('/home/barangkeluar','Home::barangkeluar');
$routes->add('/home/Pesanan','Home::Pesanan');
$routes->add('/home/statusto/(:num)','Home::statusto/$1');
$routes->add('/home/statustd/(:num)','Home::statustd/$1');
$routes->add('/home/resetpassword/(:num)','Home::resetpassword/$1');
$routes->get('home/detailuser/(:num)', 'Home::detailuser/$1');
$routes->add('/home/profile','Home::profile');
$routes->post('home/aksi_profile', 'Home::aksi_profile');
$routes->post('home/aksi_eprofile', 'Home::aksi_eprofile');
$routes->post('home/aksi_changepass', 'Home::aksi_changepass');
$routes->add('/home/changepassword','Home::changepassword');
$routes->add('/home/printnota/(:segment)', 'Home::printnota/$1');
$routes->add('/home/printnota/(:segment)', 'Home::printnota/$1');
$routes->add('/home/dkeranjang/(:segment)', 'Home::dkeranjang/$1');
$routes->add('/home/laporantransaksi','Home::laporantransaksi');
$routes->add('/home/transaksi_pdf','Home::transaksi_pdf');
$routes->add('/home/transaksi_excel','Home::transaksi_excel');
$routes->add('/home/transaksi_windows','Home::transaksi_windows');
$routes->add('/home/filtertanggalbm','Home::filtertanggalbm');
$routes->add('/home/laporanbarangmasuk','Home::laporanbarangmasuk');
$routes->add('/home/barangm_pdf','Home::barangm_pdf');
$routes->add('/home/tbarangm','Home::tbarangm');
$routes->add('/home/barangm_excel','Home::barangm_excel');
$routes->add('/home/barangm_windows','Home::barangm_windows');
$routes->get('/home/filtertanggalbk','Home::filtertanggalbk');
$routes->add('/home/laporanbarangkeluar','Home::laporanbarangkeluar');
$routes->add('/home/barangk_pdf','Home::barangk_pdf');
$routes->add('/home/barangk_excel','Home::barangk_excel');
$routes->add('/home/barangk_windows','Home::barangk_windows');
$routes->get('/home/ruser','Home::ruser');
$routes->add('/home/rbarangkeluar','Home::rbarangkeluar');
$routes->add('/home/rbarangmasuk','Home::rbarangmasuk');
$routes->add('/home/huser/(:num)','Home::huser/$1');
$routes->get('home/sdkeranjang/(:any)', 'Home::sdkeranjang/$1');
$routes->get('/home/datakeranjang','Home::datakeranjang');
$routes->get('home/sddatakeranjang/(:any)', 'Home::sddatakeranjang/$1');
$routes->get('/home/epemesanan/(:segment)', 'Home::epemesanan/$1');
$routes->get('home/rsdatakeranjang/(:any)', 'Home::rsdatakeranjang/$1');
$routes->get('/home/filtertanggal', 'Home::filtertanggal');
$routes->get('/home/tkeranjang', 'Home::tkeranjang');
$routes->get('/home/rtransaksi', 'Home::rtransaksi');
$routes->get('/home/transaksi', 'Home::transaksi');
$routes->get('/home/ekeranjang/(:segment)', 'Home::ekeranjang/$1');
$routes->get('/home/ekeranjangp/(:segment)', 'Home::ekeranjangp/$1');
$routes->post('/home/addItem', 'Home::addItem');
$routes->post('/home/addItem2', 'Home::addItem2');
$routes->get('home/pay/(:segment)', 'Home::pay/$1');
$routes->post('/home/updateCart/(:num)', 'Home::updateCart/$1');
$routes->post('/home/removeCart/(:num)', 'Home::removeCart/$1');
$routes->post('/home/updateTotalPrice', 'Home:: updateTotalPrice');
$routes->get('/home/tbarangk', 'Home::tbarangk');
$routes->get('home/ebarangk/(:num)', 'Home::ebarangk/$1');
$routes->add('/home/etransaksi/(:num)','Home::etransaksi/$1');
$routes->get('/home/sduser/(:num)','Home::sduser/$1');
$routes->add('/home/sdtransaksi/(:num)','Home::sdtransaksi/$1');
$routes->add('/home/rstransaksi/(:num)','Home::rstransaksi/$1');
$routes->add('/home/htransaksi/(:num)','Home::htransaksi/$1');
$routes->post('home/aksi_profile', 'Home::aksi_profile');
$routes->post('home/aksi_etransaksi', 'Home::aksi_etransaksi');
$routes->post('home/aksi_tbarangm', 'Home::aksi_tbarangm');
$routes->get('/home/signup', 'Home::signup');
$routes->post('home/aksi_signup', 'Home::aksi_signup');
$routes->add('/home/hbarang/(:num)','Home::hbarang/$1');
$routes->add('/home/rsuser/(:num)','Home::rsuser/$1');